"""Extraction layer v2: discriminated-union schemas para output del LLM."""

from src.extraction.schema_v2 import (
    ColumnaValor,
    CuotaFijaAdicional,
    CuotaFijaEscalonadaSchema,
    CuotaFijaSimpleSchema,
    FilaCuotaFijaEscalonada,
    FilaCuotaFijaSimple,
    FilaMixta,
    FilaProgresiva,
    FilaTarifaMillar,
    FilaTasaUnica,
    MetaExtraccion,
    MinimoPredial,
    MixtoSchema,
    OtroNoClasificadoSchema,
    PredialOutputV2,
    PredialSchemaV2,
    ProgresivoSchema,
    TarifaMillarSchema,
    TasaUnicaSchema,
)

__all__ = [
    "ColumnaValor",
    "CuotaFijaAdicional",
    "CuotaFijaEscalonadaSchema",
    "CuotaFijaSimpleSchema",
    "FilaCuotaFijaEscalonada",
    "FilaCuotaFijaSimple",
    "FilaMixta",
    "FilaProgresiva",
    "FilaTarifaMillar",
    "FilaTasaUnica",
    "MetaExtraccion",
    "MinimoPredial",
    "MixtoSchema",
    "OtroNoClasificadoSchema",
    "PredialOutputV2",
    "PredialSchemaV2",
    "ProgresivoSchema",
    "TarifaMillarSchema",
    "TasaUnicaSchema",
]
